### PR TITLE
Validate expiration date for public links only

### LINKED ISSUE #287: Cannot create ordinary share with users when public link expiry is set
Set public link expiration policies:
Screenshot_2020-03-11 Settings - ownCloud(3)

Have no core policies about expiration dates (for public link, user or group shares).

Try to share:
Screenshot_2020-03-11 Files - ownCloud(3)

The share does not get created.

The same problem happens when sharing with a group.

### PR DESCRIPTION
**Pull request by VicDeo**
Depends on https://github.com/owncloud/core/pull/37135
Fixes #287 
### TODO
- [x] add an unit test to cover user/group/public link shares separately

### CODE REVIEW

**Comment by phil-davis** [comment]
@VicDeo I pushed acceptance tests:
1) test scenarios that demonstrate the bug (those pass in current master of password_policy)
2) adjustments to the test scenarios to test what is the really desired correct behaviour (those pass in this PR)

Please pull from GitHub, and add whatever unit tests you want. Then IMO we are done.

**Comment by VicDeo** [comment]
@phil-davis great, thanks!

**Comment by VicDeo** [comment]
@phil-davis unit tests have been updated

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/password_policy/1210/43/10 acceptance tests fail because in drone CI the "current" daily-master-qa tarball is used as the core "server-under-test" and the current password_policy app code from this PR is used.

daily-master-qa tarball is now stale - the related/needed fix in core was only merged a few hours ago. We need someone to build a new daily-master-qa tarball, or wait until tomorrow.

**Comment by phil-davis** [comment]
I rebased just now, because #294 was merged.

We will need to restart CI again tomorrow after the core daily-master-qa tarball gets updated overnight.

**Pull request merged**
