### PR TITLE
Fix OldPasswordMapper for Oracle

### PR DESCRIPTION
**Pull request by PVince81**
@phil-davis can you run the Oracle drone here ?

Not sure on what branch you got the results from https://github.com/owncloud/password_policy/issues/101 ...

Fixes https://github.com/owncloud/password_policy/issues/101

### CODE REVIEW

**Comment by PVince81** [comment]
tested locally, to_char doesn't exist for mysql. I'll add an Oracle condition...

**Comment by PVince81** [comment]
added if statement for Oracle

**Comment by phil-davis** [comment]
This was based off some old point of master, so it had no ``.drone.yml`` and no acceptance test code.
I am rebasing to latest master, then will add Oracle drone.

**Comment by PVince81** [comment]
maybe I pushed too fast and forgot "--force" and context-switched too fast.

anyway, I added a new commit with the condition now, let's see

**Pull request merged**
