### PR TITLE
Adjust maximum days to 750

### PR DESCRIPTION
**Pull request by IljaN**

### CODE REVIEW

**Comment by phil-davis** [comment]
The errors in Oracle drone CI pipelines were because of issue https://github.com/owncloud/files_classifier/issues/786
That has been fixed. I will restart drone CI for this PR.

**Comment by phil-davis** [comment]
@IljaN you could cherry-pick the commit from PR #401 into this branch and those tests should pass.

**Comment by IljaN** [comment]
@phil-davis done

**Review by jvillafanez — APPROVED** [review]

**Comment by phil-davis** [comment]
I will have a look at the drone CI and see what adjustment is needed...

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/password_policy/2859/62/6
```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
fatal: the remote end hung up unexpectedly
```
It is just a silly drone to GitHub network error. I restarted CI.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Release issue #403 created

**Pull request merged**
